
services:
  redis:
    image: redis:8.2.0
    networks:
      - overlay-net
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - /data/redis:/data

  redis-insight:
    image: redis/redisinsight:2.70
    networks:
      - overlay-net
    environment:
      - RI_REDIS_HOST=redis

networks:
  overlay-net:
    external: true
